<h2>Connection</h2>
<section>
    <?php if ($this->error): ?>
        <p class="error">Des erreurs sont intervenues durant la validation du formulaire.</p>
    <?php endif; ?>
    <p>
        <?php
        $form = $this->mongoAuthForm;
        $form->setAttribute('action', $this->url(null, ['controller'=>'Connection', 'action'=>'connect']));
        echo $this->form()->render($form);
        ?>
    </p>
    <a href="/mongomyadmin"><< return Home</a>
</section>

<style>
	form label{
		display: block;
	}
	
	form label span{
		width: 20%;
		display: inline-block;
	}
	
	form label input{
		width: 80%;
	}
</style>