<h2>Add Document in <?php echo $this->collection; ?></h2>
<section>
    <?php if ($this->error): ?>
        <p class="error">Des erreurs sont intervenues durant la validation du formulaire.</p>
    <?php endif; ?>
    <p>
        <?php
        $form = $this->mongoAddDocumentForm;
        $form->setAttribute('action', $this->url(null, ['controller'=>'Index', 'action'=>'add']));
        echo $this->form()->render($form);
        ?>
    </p>
    <a href="/mongomyadmin?collection=<?php echo $this->collection;?>"><< return to Collection</a>
</section>