<div class="container">
	<div class="row">
		<div class="col-sm-3">
			<h3>Database : <?php echo $this->database; ?></h3>
			<ul>
			<?php 
				$collections = $this->collections;
				foreach ($collections as $collection){ ?>
					<li><a href="/mongomyadmin/index?collection=<?php echo $collection->getName(); ?>"><?php echo $collection->getName(); ?></a></li>		
				<?php }
			?>
			</ul>
		</div>
		<div class="col-sm-9">
			<?php
			require_once 'menu.phtml';
			?>
			<?php if(isset($_GET["collection"]) && $_GET["collection"] != ""){?>
				<table border="1" width="100%">
					<tr>
						<th>Actions</th>
						<?php foreach ($this->header as $key){ ?>
							<th><?php echo $key; ?></th>
						<?php }?>
					</tr>
					<?php foreach ($this->cursor as $doc){ ?>
						<tr>
							<td>
								<a href="/mongomyadmin/index/update?collection=<?php echo $_GET["collection"];?>&id=<?php echo $doc["_id"];?>">Update</a> |
								<a href="/mongomyadmin/index/remove?collection=<?php echo $_GET["collection"];?>&id=<?php echo $doc["_id"];?>">Remove</a>
							</td>
						<?php foreach ($doc as $key => $value){ ?>
							<td><?php echo $value; ?></td>
						<?php } ?>
						</tr>
					<?php }?>
				</table>
				<br/>
				<a href="/mongomyadmin/index/add?collection=<?php echo $_GET["collection"];?>">Add Document</a>
			<?php }?>
		</div>
	</div>
</div>